### ISSUE TITLE
For Demo

### ISSUE THREAD

**Issue by jayeshtechextensor** [DeveloperOnCall/laravel-mt5webapi#1]
Hello DeveloperOnCall,

How are you! Hope you are well!

I am new to Github. I checked your project features I like this.

But can you please tell me in this project "Account Position" values simultaneously updated or not on every one second (without page refresh) this feature is available or not?

Suppose if this feature is available then how can I buy this project? (Project Buy link is not working)

Can you please share your email id/ Contact No./ Skype ID we can detail in discussion this project

Thank you in advance,

**Comment by imranshahid790** [comment]
how can I buy this project ???? kindly share contact no plz

**Comment by DeveloperOnCall** [comment]
This package was recently updated and transferred [HERE](https://nerdsnipe.github.io/mt5webapi/)
